### PR TITLE
Add link to 9447-ctf danklang writeup

### PR DESCRIPTION
**Pull request by auscompgeek**
Huzzah, an actual writeup!

### CODE REVIEW

**Comment by YASME-Tim** [comment]
Just did add it from my IRC logs :S. I'll just merge this one

**Comment by auscompgeek** [comment]
Darn, went to so much trouble to fork the repo. :P

**Comment by YASME-Tim** [comment]
@auscompgeek You can also just use the browser for single links (Edit a file via browser => forks without trouble). Forking the repo late in the year equals downloading XGB :D

**Comment by auscompgeek** [comment]
True, true. I was going to edit the 9447 README as well though before I realised reversing/danklang was already moved to the relevant section.

**Pull request merged**
