### PR TITLE
:memo: added steganography/imaged for 9447 CTF

### PR DESCRIPTION
**Pull request by stefan2904**

### CODE REVIEW

**Comment by auscompgeek** [comment]
You… might want to run a spell check on this.

**Comment by YASME-Tim** [comment]
Thanks @stefan2904 . @auscompgeek because of chun(c)ks?

**Comment by auscompgeek** [comment]
@YASME-Tim Yeah, precisely that. I didn't go through to find any other spelling errors though.

**Comment by YASME-Tim** [comment]
@auscompgeek welp, vim spellchecker did not find anything else :)

**Pull request merged**
