### PR TITLE
Add fuckup binary

### PR DESCRIPTION
**Pull request by zachriggle**

### CODE REVIEW

**Comment by dhanvi** [comment]
@zachriggle Thanks for the files :+1: 

@YASME-Tim how could you miss them ??

**Comment by dhanvi** [comment]
screenshot from 2015-05-19 02 48 30

Hope he didn't miss anything more :smile:

**Comment by YASME-Tim** [comment]
Well I thought they were connect only. Must have been blind to not see any link in the descriptions

**Comment by dhanvi** [comment]
Any way leave it :smile: we got them now :+1:

**Pull request merged**
