### PR TITLE
Add team, forgot, echo, concealed, medusa, noname external writeup

### PR DESCRIPTION
**Pull request by HAMIDx9**
Add team, forgot, echo, concealed, medusa, noname external writeup

### CODE REVIEW

**Comment by dhanvi** [comment]
@HAMIDx9 I still got conflicts you need fetch the recent changes :+1:

**Comment by HAMIDx9** [comment]
@dhanvi  Seems confilicts fixed. if it is needed to create a new pull request tell me.
Thanks

**Comment by dhanvi** [comment]
@HAMIDx9 I have added the writeup in this commit 6118fe772c56bc930d0ab12372ed6c69e6c4a807

**Comment by HAMIDx9** [comment]
Thanks

**Pull request closed without merging**
