### PR TITLE
Added link to external write up for insomnidroid part 2 in Insomni'hack CTF

### PR DESCRIPTION
**Pull request by cryptax**

### CODE REVIEW

**Comment by YASME-Tim** [comment]
@cryptax Can you pull/update the local repo on your side again and issue a new pull-request? It got merge conflicts and that would be an easier solution to merge

**Comment by cryptax** [comment]
Ok - I've pulled and updated. Should be ok now?

**Comment by dhanvi** [comment]
@cryptax better complete change in a single commit or squash the commits to one :smile:

**Comment by dhanvi** [comment]
@cryptax added the external link here 15e854fd66520fab4f72d1d4b72ce2f8d3041d94

**Pull request closed without merging**
