### PR TITLE
Add team, forgot, echo, concealed, medusa, noname external writeup

### PR DESCRIPTION
**Pull request by HAMIDx9**
Add team, forgot, echo, concealed, medusa, noname external writeup

### CODE REVIEW

**Comment by YASME-Tim** [comment]
Wow very nice @HAMIDx9 !! @dhanvi Can you check all pull requests? Got no time today, thanks :)

**Comment by dhanvi** [comment]
@YASME-Tim I am on my way merging the pull requests 

@HAMIDx9 would you mind creating a new pull request or I can add the blogs for you :smile:

**Comment by HAMIDx9** [comment]
@dhanvi I pull a new request ASAP.
Thanks

**Comment by dhanvi** [comment]
@YASME-Tim seems like every thing is clean now :+1:

**Pull request closed without merging**
