### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mrexcessive**
:link: Added WhitehattersAcademy captcha writeup

### CODE REVIEW

**Comment by dhanvi** [comment]
Well @mrexcessive I appreciate you adding you many links that helps us a lot :+1: 

but please do add everything you have at one time not one at a time for example like 4b1218f147fccfcdbe24064983448a56f2211ca1 

you are making our this thing a lot messy, btw are you using the web interface of git to create this pull request ?? If so you better change that way and use git

**Comment by mrexcessive** [comment]
Hi - am using Web interface... haven't used git to make a change to online
repo before ;)  - noob yes I know....
Web interface seems pretty straightforward ?

**Comment by dhanvi** [comment]
Well I do know that it's hard to get things started but it once you start using git you fell a lot better believe me I have also done it like this when I don't know about git 

Well the IMO the web interface don't gives you all the power you have with the git :( 

I suggest you read this good book https://progit2.s3.amazonaws.com/en/2015-05-02-7ddee/progit-en.478.pdf

**Comment by mrexcessive** [comment]
Thank you ;)

**Pull request merged**
