### PR TITLE
:link: Add new writeup link for reverse/access-control

### PR DESCRIPTION
**Pull request by jaybosamiya**

### CODE REVIEW

**Comment by jaybosamiya** [comment]
The extra commit is because I forgot to follow the guidlines for commit messages

**Comment by dhanvi** [comment]
Well how about creating a new branch and submitting the link. 

Or I can add the link for you :smile:

**Comment by dhanvi** [comment]
Well you can reduce the commit next time :smile:

**Comment by jaybosamiya** [comment]
Will definitely do so next time. Thanks :)

**Pull request merged**
