### PR TITLE
Add exodus adventure

### LINKED ISSUE #177: ExodusIntel CTF
Exodus hosted a CTF over the weekend.  It's available here:

https://ctf.exodusintel.com/adventure/

In particular, you need the ELF binary *and* all assets on the linked web-page.  That specific JSLinux implementation is necessary to complete one of the challenges.  I'm not sure how you want to handle that, since it pulls things on-the-fly over the wire.

### PR DESCRIPTION
**Pull request by zachriggle**
Closes #177

### CODE REVIEW

**Comment by zachriggle** [comment]
I have received permission from Fabrice to re-host JSLinux.

```
Message-ID: <552E8E56.3040203@bellard.org>
Date: Wed, 15 Apr 2015 18:14:14 +0200
From: Fabrice Bellard <fabrice@bellard.org>
To: Zach Riggle <riggle@google.com>
Subject: Re: Redistribution of JSLinux

You have my permission.

Best regards,

Fabrice.

On 04/15/2015 06:10 PM, Zach Riggle wrote:
> Fabrice
>
> Last weekend, Exodus Intel hosted a small CTF/crackme competition, which
> made use of a modified version of JSLinux.
>
> https://ctf.exodusintel.com/adventure
>
> I would like to re-host this challenge on Github for posterity:
>
> https://github.com/ctfs/write-ups-2015/pull/178
>
> Per the copyright, I'm seeking your approval to redistribute this
> modified version of JSLinux.
>
> Zach
```

**Comment by YASME-Tim** [comment]
@zachriggle  It's ~62MB right? Maybe it's better to re-host it on a different repo to keep this repo as small as possible. On the other hand, there are some CTFs with 50MB+ in our write-ups repos. Let me think about this PR for another day, thanks for taking time to get the source of exodus + asking for permission

**Comment by zachriggle** [comment]
I've tar/xz'ed the files, reducing the size from 60MB to 13MB.  I amended the commit so the original, uncompressed files do not appear in the repository.

**Comment by zachriggle** [comment]
Just kidding actually fixed the commit size now.

**Comment by dhanvi** [comment]
Well @YASME-Tim I think we can merge this one now ?

**Pull request merged**
