### PR TITLE
:book: Translate Challange and fix some readme

### PR DESCRIPTION
**Pull request by abdilahrf**
let me know if , missing translate at question

### CODE REVIEW

**Comment by YASME-Tim** [comment]
@abdilahrf I'll try to merge it soon, it currently has merge conflicts. Can you check that every file can be opened, especially the password-protected ones, if there are any? Also do you have any writeups or flags for these challenges? E.g. the flags for the crypto challenges will be, I guess, in Indonesian, so any non-Indonesian speaker will never find it, without it being wrapped in any flag format. Is there a flag format?

**Comment by abdilahrf** [comment]
@YASME-Tim : the flag doesn't have format at all but in some case the flag started with , Flag : x
and i will post the writeup with the flag as soon as possible

**Comment by dhanvi** [comment]
@YASME-Tim try to merge it soon or ask @abdilahrf to create a new pull request :+1:

**Comment by abdilahrf** [comment]
let me create new pull request

**Comment by dhanvi** [comment]
@abdilahrf that a good thing to do :smiley:

**Pull request closed without merging**
