### PR TITLE
qttpd part 1 - external write up

### PR DESCRIPTION
**Pull request by JamieH**
The whitehatters blog post on qttpd part 1

### CODE REVIEW

**Comment by dhanvi** [comment]
@JamieH it's still having conflicts I will add them for you :smile:

**Comment by dhanvi** [comment]
next time don't forget to fetch all the things before you create a pull request :smile:

**Comment by JamieH** [comment]
Thanks @dhanvi I pulled like right before I did the edits and then did them and it was like "no" and then realised someone has pushed :panda_face:

**Comment by dhanvi** [comment]
Well since this is not exactly a development repo and you will need to get the things always from the repo 

alternatively you can create a issue with the link and the question name we will do it for you 

btw thanks for the link :smiley:

**Pull request closed without merging**
