### PR TITLE
Dakotacon RE Challenge 2015

### PR DESCRIPTION
**Pull request by Spirotot**

### CODE REVIEW

**Comment by dhanvi** [comment]
@YASME-Tim @mathiasbynens should we have to merge this pull request as it is not a complete ctf

http://dakotacon.org/docs/REPromo.pdf

**Comment by lionaneesh** [comment]
Plus, we have no knowledge of any other tasks in the CTF. Won't we have to setup the skeleton with all the task descriptions first?

**Comment by Spirotot** [comment]
The CTF consisted of only reverse-engineering tasks.

Within the CTF itself, challenges were organized by language: C, C++,
JavaScript, C#/.NET, PDF, and PHP.

**Comment by lionaneesh** [comment]
@Spirotot Is there a resource for the other tasks, where we can get the description of the task and all the requisite resources.

**Comment by Spirotot** [comment]
@lionaneesh Well, http://thectf.net (where the contest was hosted) has been taken down, so the descriptions (which were rather short, if I remember correctly -- and did not hint at the solution) are no longer available.

I do have all the original zips/binaries still on my hard drive, though!

**Comment by lionaneesh** [comment]
Can you send them to me? my email: lionaneesh@gmail.com.

**Comment by Spirotot** [comment]
@lionaneesh Done!

**Comment by lionaneesh** [comment]
Thanks a lot! If other's agree. I'll create a skeleton for the ctf and then
we can add your writeup for C2. :)

**Comment by Spirotot** [comment]
Sounds like a plan!

**Comment by YASME-Tim** [comment]
@lionaneesh Don't forget to use the [genctf tool](https://github.com/ctfs/write-ups-tools/tree/master/genctf) to make the work a bit less tedious ;). @Spirotot Thanks for keeping the descriptions+files!

**Comment by dhanvi** [comment]
@lionaneesh are you doing any thing regarding this placeholders 

I will keep the place holders for you if you can forward the email with tasks to me or I will close this issue

**Comment by dhanvi** [comment]
Since have no activity around here I am closing this PR 

@lionaneesh feel free to add the files and open it again

**Pull request closed without merging**
